project:
  type: website
  output-dir: docs

website:
  title: "Chart & Chill ðŸ“Š"
  navbar:
    left:
      - href: index.qmd
        text: "Startseite"
      - href: erste-schritte.qmd
        text: "Erste Schritte"
      - href: lektionen.qmd
        text: "Lektionen"
      - href: galerie.qmd
        text: "Galerie"
      - href: ueber.qmd
        text: "Ãœber"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
